version: "3.0"
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_db_volume:
    external: true